# Generated by Django 5.2 on 2025-04-26 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='description2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='wesite_url',
            field=models.URLField(blank=True),
        ),
    ]
