# Generated by Django 5.2 on 2025-04-28 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description2',
        ),
    ]
