# Generated by Django 5.2 on 2025-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tasks_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
